# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5a82b787f42f23af104a0920ecf02d600a8f946edb6177af95af8a5b040ccf49f080adbcad76864b580a162647fafa9852c664203956d730c15c1b85d8b5ae7

test:
  secret_key_base: 77c56aaa03bf404b4a91a200a10124b43952884d9afdd067e67f42fa5ae5f38360e39c5702f67977983c3f4798c8acd7fd63989d7ef1000ab7ab71e80837505b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
